import ctypes
from ctypes import c_int32, c_float, c_wchar

class SPageFileStatic(ctypes.Structure):
    _pack_ = 4
    _fields_ = [
        ('_smVersion', c_wchar * 15),
        ('_acVersion', c_wchar * 15),
        ('numberOfSessions', c_int32),
        ('numCars', c_int32),
        ('carModel', c_wchar * 33),
        ('track', c_wchar * 33),
        ('playerName', c_wchar * 33),
        ('playerSurname', c_wchar * 33),
        ('playerNick', c_wchar * 33),
        ('sectorCount', c_int32),
        ('maxTorqueNOTUSED', c_float),
        ('maxPowerNOTUSED', c_float),
        ('maxRpm', c_int32),
        ('maxFuel', c_float),
        ('suspensionMaxTravelNOTUSED', c_float * 4),
        ('tyreRadiusNOTUSED', c_float * 4),
        ('maxTurboBoostNOTUSED', c_float),
        ('depreciated_1NOTUSED', c_float),
        ('depreciated_2NOTUSED', c_float),        
        ('penaltiesEnabled', c_int32),
        ('aidFuelRate', c_float),
        ('aidTireRate', c_float),
        ('aidMechanicalDamage', c_float),
        ('aidAllowTyreBlankets', c_int32),
        ('aidStability', c_float),
        ('aidAutoClutch', c_int32),
        ('aidAutoBlip', c_int32),
        ('hasDRSNOTUSED', c_int32),
        ('hasERSNOTUSED', c_int32),
        ('hasKERSNOTUSED', c_int32),
        ('kersMaxJNOTUSED', c_float),
        ('engineBrakeSettingsCountNOTUSED', c_int32),
        ('ersPowerControllerCountNOTUSED', c_int32),
        ('trackSplineLengthNOTUSED', c_float),
        ('trackConfigurationNOTUSED', c_wchar * 33),
        ('ersMaxJNOTUSED', c_float),
        ('isTimedRaceNOTUSED', c_int32),
        ('hasExtraLapNOTUSED', c_int32),
        ('carSkinNOTUSED', c_wchar * 33),
        ('reversedGridPositionsNOTUSED', c_int32),
        ('pitWindowStart', c_int32),
        ('pitWindowEnd', c_int32),
        ('isOnline', c_int32), 
        ('dryTyresName', c_wchar * 33), 
        ('wetTyresName', c_wchar * 33)
    ]