import ctypes
from ctypes import c_int32, c_float, c_wchar

class SPageFilePhysics(ctypes.Structure):
    _pack_ = 4
    _fields_ = [
        ('packetId', c_int32),
        ('gas', c_float),
        ('brake', c_float),
        ('fuel', c_float),
        ('gear', c_int32),
        ('rpm', c_int32),
        ('steerAngle', c_float),
        ('speedKmh', c_float),
        ('velocity', c_float * 3),
        ('accG', c_float * 3),
        ('wheelSlip', c_float * 4),
        ('wheelLoadNOTUSED', c_float * 4),
        ('wheelPressure', c_float * 4),
        ('wheelAngularSpeed', c_float * 4),
        ('tyreWearNOTUSED', c_float * 4),
        ('tyreDirtyLevelNOTUSED', c_float * 4),
        ('tyreCoreTemperature', c_float * 4),
        ('camberRADNOTUSED', c_float * 4),
        ('suspensionTravel', c_float * 4),
        ('drsNOTUSED', c_float),
        ('tc', c_float),
        ('heading', c_float),
        ('pitch', c_float),
        ('roll', c_float),
        ('cgHeightNOTUSED', c_float),
        ('carDamage', c_float * 5),
        ('numberOfTyresOutNOTUSED', c_int32),
        ('pitLimiterOn', c_int32),
        ('abs', c_float),
        ('kersChargeNOTUSED', c_float),
        ('kersInputNOTUSED', c_float),
        ('autoShifterOn', c_int32),
        ('rideHeightNOTUSED', c_float * 2),
        ('turboBoost', c_float),
        ('ballastNOTUSED', c_float),
        ('airDensityNOTUSED', c_float),
        ('airTemp', c_float),
        ('roadTemp', c_float),
        ('localAngularVel', c_float * 3),
        ('finalFF', c_float),
        ('performanceMeterNOTUSED', c_float),
        ('engineBrakeNOTUSED', c_int32),
        ('ersRecoveryLevelNOTUSED', c_int32),
        ('ersPowerLevelNOTUSED', c_int32),
        ('ersHeatChargingNOTUSED', c_int32),
        ('ersIsChargingNOTUSED', c_int32),
        ('kersCurrentKJNOTUSED', c_float),
        ('drsAvailableNOTUSED', c_int32),
        ('drsEnabledNOTUSED', c_int32),
        ('brakeTemp', c_float * 4),
        ('clutch', c_float),
        ('tyreTempINOTUSED', c_float * 4),
        ('tyreTempMNOTUSED', c_float * 4),
        ('tyreTempONOTUSED', c_float * 4),
        ('isAIControlled', c_int32),
        ('tyreContactPoint', c_float * 4 * 3),
        ('tyreContactNormal', c_float * 4 * 3),
        ('tyreContactHeading', c_float * 4 * 3),
        ('brakeBias', c_float),
        ('localVelocity', c_float * 3),
        ('P2PActivationNOTUSED', c_int32), 
        ('P2PStatusNOTUSED', c_int32), 
        ('currentMaxRpmNOTUSED', c_float), 
        ('mzNOTUSED', c_float), 
        ('fxNOTUSED', c_float), 
        ('fyNOTUSED', c_float), 
        ('slipRation', c_float * 4), 
        ('slipAngle', c_float * 4), 
        ('tcinActionNOTUSED', c_int32), 
        ('absInActionNOTUSED', c_int32), 
        ('suspensionDamageNOTUSED', c_int32 * 4), 
        ('tyreTempNOTUSED', c_int32 * 4), 
        ('waterTemp', c_float), 
        ('brakePressure', c_float * 4), 
        ('frontBrakeCompund', c_int32), 
        ('rearBrakecompound', c_int32), 
        ('padLife', c_float * 4), 
        ('discLife', c_float * 4), 
        ('ignitionOn', c_int32), 
        ('starterEngineOn', c_int32), 
        ('isEngineRunning', c_int32), 
        ('kerbVibration', c_float), 
        ('slipVibrations', c_float), 
        ('gVibrations', c_float), 
        ('absVibrations', c_float)
    ]